server {
    listen 2;
    server_name example.com;

    location /app {
        root /var/www/app;
    }

    location /app/api {
        root /var/www/api;
    }
}


server
{
    listen 3;
    server_name example.com;

    location /app {
        root /var/www/app;
    }

    location /app/api {
        root /var/www/api;
    }
}

server
{
    listen 4;
    server_name example.com;
    location /app
    {
        root /var/www/app;
    }
    location /app/api
    {
        root /var/www/api;
    }
}